Require collector_url
Fixes:

    'NoneType' object has no attribute 'strip'
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/temboardagent/scheduler/taskmanager.py", line 809, in exec_worker
        res = getattr(sys.modules[module], function)(*args, **kws)
      File "/usr/lib/python2.7/site-packages/temboardagent/scripts/agent.py", line 99, in wrapper
        return function(app=self.app, *a, **kw)
      File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/__init__.py", line 205, in monitoring_sender_worker
        msg.content
      File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/output.py", line 34, in send_output
        data=json.loads(j_output)
      File "/usr/lib/python2.7/site-packages/temboardagent/httpsclient.py", line 90, in https_request
        request = RequestWithMethod(url, data=json.dumps(data), method=method)
      File "/usr/lib/python2.7/site-packages/temboardagent/httpsclient.py", line 67, in __init__
        urllib2.Request.__init__(self, *args, **kwargs)
      File "/usr/lib64/python2.7/urllib2.py", line 229, in __init__
        self.__original = unwrap(url)
      File "/usr/lib64/python2.7/urllib.py", line 1071, in unwrap
        url = url.strip()
    AttributeError: 'NoneType' object has no attribute 'strip'