autossl: Initialize HTTP connection request headers
Required by Tornado 6.

Fixes:

    DEBUG: Redirecting client to https://0.0.0.0:8888/.
    ERROR: Failed to process HTTP request:
    ERROR: Traceback (most recent call last):
    ERROR:   File "/home/bersace/src/dalibo/temboard/temboardui/autossl.py", line 225, in handle_stream
    ERROR:     yield ssl_stream.wait_for_handshake()
    ERROR:   File "/home/bersace/.cache/pyenv/versions/3.6.8/envs/tb-py3/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    ERROR:     value = future.result()
    ERROR: temboardui.autossl.SSLErrorHTTPRequest
    ERROR:
    ERROR: During handling of the above exception, another exception occurred:
    ERROR:
    ERROR: Traceback (most recent call last):
    ERROR:   File "/home/bersace/src/dalibo/temboard/temboardui/autossl.py", line 230, in handle_stream
    ERROR:     yield self.handle_http_connection(conn)
    ERROR:   File "/home/bersace/.cache/pyenv/versions/3.6.8/envs/tb-py3/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    ERROR:     value = future.result()
    ERROR:   File "/home/bersace/.cache/pyenv/versions/3.6.8/envs/tb-py3/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    ERROR:     yielded = ctx_run(next, result)
    ERROR:   File "/home/bersace/.cache/pyenv/versions/3.6.8/envs/tb-py3/lib/python3.6/site-packages/tornado/gen.py", line 162, in _fake_ctx_run
    ERROR:     return f(*args, **kw)
    ERROR:   File "/home/bersace/src/dalibo/temboard/temboardui/autossl.py", line 281, in handle_http_connection
    ERROR:     headers=response.headers,
    ERROR:   File "/home/bersace/.cache/pyenv/versions/3.6.8/envs/tb-py3/lib/python3.6/site-packages/tornado/http1connection.py", line 401, in write_headers
    ERROR:     assert self._request_headers is not None
    ERROR: AssertionError