agent: Depends on setuptools in deb
Fixes:

    Traceback (most recent call last):
    File "/usr/bin/temboard-agent", line 5, in <module>
        from temboardagent.__main__ import main
    File "/usr/lib/python3/dist-packages/temboardagent/__main__.py", line 5, in <module>
        from .cli.app import app
    File "/usr/lib/python3/dist-packages/temboardagent/cli/app.py", line 17, in <module>
        from ..toolkit import taskmanager, validators as v
    File "/usr/lib/python3/dist-packages/temboardagent/toolkit/validators.py", line 15, in <module>
        from distutils.util import strtobool
    ModuleNotFoundError: No module named 'distutils.util'