agent: Use dbname instead of database
Fixes:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/temboardagent/toolkit/taskmanager.py", line 627, in exec_worker
        res = fun(*args, **kws)
      File "/usr/lib/python3/dist-packages/temboardagent/toolkit/taskmanager.py", line 802, in wrapper
        return function(self.app, *a, **kw)
      File "/usr/lib/python3/dist-packages/temboardagent/plugins/maintenance/__init__.py", line 170, in analyze_worker
        with app.postgres.connect(database=dbname) as conn:
      File "/usr/lib/python3/dist-packages/temboardagent/postgres.py", line 83, in connect
        return closing(retry_connect(connect, self.app, **kw))
      File "/usr/lib/python3/dist-packages/temboardagent/postgres.py", line 299, in retry_connect
        conn = connect(*a, **kw)
      File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 121, in connect
        dsn = _ext.make_dsn(dsn, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/psycopg2/extensions.py", line 151, in make_dsn
        raise TypeError(
    TypeError: you can't specify both 'database' and 'dbname' arguments