ui: Don't hide unhandled error in 400
Also fixes:

    Traceback (most recent call last):
      File "/home/bersace/src/dalibo/temboard/ui/temboardui/toolkit/app.py", line 348, in entrypoint
        retcode = self.main(argv, environ)
      File "/home/bersace/src/dalibo/temboard/ui/temboardui/cli/app.py", line 142, in main
        return command.main(args)
      File "/home/bersace/src/dalibo/temboard/ui/temboardui/cli/register_instance.py", line 98, in main
        instance = get_instance(session, args.agent_address, args.agent_port)
      File "/home/bersace/src/dalibo/temboard/ui/temboardui/application.py", line 368, in get_instance
        raise TemboardUIError(str(e))
    TypeError: __init__() missing 1 required positional argument: 'message'