Use str() for Exception instead of 'message' attribute for python3 compat
Most Exception objects have no 'message' attribute in Python 3.

This resolves this kind of errors in logs:

    [taskmanager] ERROR:     data = metrics.get_metrics(app)
    [taskmanager] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/plugins/dashboard/metrics.py", line 16, in get_metrics
    [taskmanager] ERROR:     with app.postgres.connect() as conn:
    [taskmanager] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/postgres.py", line 73, in __enter__
    [taskmanager] ERROR:     raise UserError("Failed to connect to Postgres: %s" % e.message)
    [taskmanager] ERROR: AttributeError: 'OperationalError' object has no attribute 'message'