Limit tornado version to 6.3
_verify_cert in SSLIOStream is removed on Tornado 6.4+
and we use it in autossl.py.
ERROR:  tornado.general: Uncaught exception, closing connection.
 Traceback (most recent call last):
 File "/usr/local/lib/python3.10/dist-packages/tornado/iostream.py", line 691, in _handle_events
  self._handle_read()
 File "/usr/local/lib/python3.10/dist-packages/tornado/iostream.py", line 1427, in _handle_read
  self._do_ssl_handshake()
 File "/usr/local/lib/python3.10/dist-packages/temboardui/autossl.py", line 159, in _do_ssl_handshake
  if not self._verify_cert(self.socket.getpeercert()):
AttributeError: 'EasySSLIOStream' object has no attribute '_verify_cert'