Force sqlalchemy version < 2
SQLAlchemy 2 introduces some changes that are no longer compatible
with the current temBoard version.

 Traceback (most recent call last):
  File "/home/plgonon/Workspace/temboard/dev/venv-py3.9/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/plgonon/Workspace/temboard/dev/venv-py3.9/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/plgonon/Workspace/temboard/ui/temboardui/web/routes.py", line 57, in home_instances
    all_availability = g.db_session.execute(sql, {}).fetchall()
  File "/home/plgonon/Workspace/temboard/dev/venv-py3.9/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/home/plgonon/Workspace/temboard/dev/venv-py3.9/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2022, in _execute_internal
    statement = coercions.expect(roles.StatementRole, statement)
  File "/home/plgonon/Workspace/temboard/dev/venv-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 413, in expect
    resolved = impl._literal_coercion(
  File "/home/plgonon/Workspace/temboard/dev/venv-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 639, in _literal_coercion
    return self._text_coercion(element, argname, **kw)
  File "/home/plgonon/Workspace/temboard/dev/venv-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 632, in _text_coercion
    return _no_text_coercion(element, argname)
  File "/home/plgonon/Workspace/temboard/dev/venv-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 602, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression '\n        SELECT\n         ...' should be explicitly declared as text('\n        SELECT\n         ...')