Fix Python3.5 kwdefaults edition
Fixes:

    json.dumps.__kwdefaults__['cls'] = JSONEncoder
    TypeError: 'NoneType' object does not support item assignment