Remove codecov from dev/requirements.txt
This package is not used anymore (the corresponding webhook has been removed).

Along the way, it fixes the following issue when running `make install-3.6`:
ERROR: No matching distribution found for codecov