Require distutils
Fixes:

    $ temboard-agent --version
    Traceback (most recent call last):
    File "/usr/bin/temboard-agent", line 5, in <module>
        from temboardagent.scripts.agent import main
    File "/usr/lib/python3/dist-packages/temboardagent/scripts/agent.py", line 12, in <module>
        from ..cli import Application
    File "/usr/lib/python3/dist-packages/temboardagent/cli.py", line 6, in <module>
        from .toolkit.app import BaseApplication
    File "/usr/lib/python3/dist-packages/temboardagent/toolkit/app.py", line 5, in <module>
        from distutils.util import strtobool
    ModuleNotFoundError: No module named 'distutils.util'