Pin docutils to 0.18
Fixes:

    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
        app.build(args.force_all, filenames)
    File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 325, in build
        self.builder.build_all()
    File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 299, in build_all
        self.build(None, summary='all source files', method='all')
    File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 355, in build
        updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
    File "/usr/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 568, in update
        self._read_serial(docnames, self.app)
    File "/usr/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 587, in _read_serial
        self.read_doc(docname, app)
    File "/usr/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 662, in read_doc
        doctree = read_doc(self.app, self, self.doc2path(docname))
    File "/usr/local/lib/python2.7/site-packages/sphinx/io.py", line 302, in read_doc
        pub.publish()
    File "/usr/local/lib/python2.7/site-packages/docutils/core.py", line 219, in publish
        self.apply_transforms()
    File "/usr/local/lib/python2.7/site-packages/docutils/core.py", line 200, in apply_transforms
        self.document.transformer.apply_transforms()
    File "/usr/local/lib/python2.7/site-packages/sphinx/transforms/__init__.py", line 96, in apply_transforms
        Transformer.apply_transforms(self)
    File "/usr/local/lib/python2.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
        transform.apply(**kwargs)
    File "/usr/local/lib/python2.7/site-packages/sphinx/transforms/__init__.py", line 251, in apply
        apply_source_workaround(n)
    File "/usr/local/lib/python2.7/site-packages/sphinx/util/nodes.py", line 57, in apply_source_workaround
        for classifier in reversed(node.parent.traverse(nodes.classifier)):
    TypeError: argument to reversed() must be a sequence

    Exception occurred:
    File "/usr/local/lib/python2.7/site-packages/sphinx/util/nodes.py", line 57, in apply_source_workaround
        for classifier in reversed(node.parent.traverse(nodes.classifier)):
    TypeError: argument to reversed() must be a sequence
    The full traceback has been saved in /tmp/sphinx-err-oSEs0I.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
    make: *** [Makefile:29: html] Error 2
    make: Leaving directory '/root/workspace/docs'

See https://blog.readthedocs.com/build-errors-docutils-0-18/ .