dév: Back to Postgres 14
Official Postgres image has broken restart due to pg_start_backup rename in
Postgres 15.

Fixes:

    Waiting for postgres0 to have network.
    Rewind pgdata to failback.
    ERROR:  function pg_start_backup(unknown) does not exist
    LINE 1: SELECT pg_start_backup('docker-rewind');
                ^
    HINT:  No function matches the given name and argument types. You might need to add explicit type casts.