Initialize database after temBoard configuration
Since we now use temBoard to initialize database, we must first
configure temBoard and then run create_repository.sh.

Fixes:

    INFO: Starting temboard-migratedb 4.0+master.
    ERROR: Invalid temboard_configfile from defaults: /etc/temboard/temboard.conf: File not found...
    CRITI: Failed to load configuration.